
version: "3.9"

services:
  # Traefik Reverse Proxy Service
  proxy:
    image: traefik:v2.11
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Client (Vue/Vuetify) Service for Production
  client:
    # *** KEY CHANGE: Use 'image' directly instead of 'build' ***
    # Replace 'your_docker_username' with your actual Docker Hub username
    # Replace 'my-vue-app-frontend:latest' with the exact tag of the image you pushed (e.g., v1.0.0)
    image: sokhay/my-vue-app-frontend:develop
    environment:
      # HOST environment variable is typically for dev servers.
      # For a pre-built Nginx image, it's not usually needed.
      # If your image's CMD still runs a dev server, it might be relevant.
      HOST: 0.0.0.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`localhost`)
      - traefik.http.routers.client.entrypoints=web
      - traefik.http.services.client.loadbalancer.server.port=5173 # Dev default port
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.2'
    #       memory: '128M'

# Define named volumes (if any, though not used by frontend in this case)
# volumes:
#   # No specific volumes needed for this static frontend deployment
